### PR TITLE
add table header to README

### PR DESCRIPTION
**Pull request by Airthe911**
reslove #2 ,
我在README里加了我的github名和姓名

### CODE REVIEW

**Review by zhicheng-ning — CHANGES_REQUESTED** [review]
As shown below,there is a code conflict.Could you please try to solve it by yourself?I believe you will gain something after resolving the conflict.
- Some tips
```git
# step1
git fetch upstream main
# step2
git rebase upstream/main
# step3 : resolve the conflict
git add your-fix-file
# step4
git rebase --continue
# step5
git push -f origin your-branch-name
```
image

**Comment by Airthe911** [comment]
I will give it a try, thank you!
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhicheng-ning/signature"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月6日(星期三) 晚上11:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhicheng-ning/signature] add table header to README (PR #11)





 
@zhicheng-ning requested changes on this pull request.
 
As shown below,there is a code conflict.Could you please try to solve it by yourself?I believe you will gain something after resolving the conflict.
  
Some tips
  # step1 git fetch upstream main # step2 git rebase upstream/main # step3 : resolve the conflict git add your-fix-file # step4 git rebase --continue # step5 git push -f origin your-branch-name

**Comment by zhicheng-ning** [comment]
by the way,there is no need to use `resolve #2`,just use `#2` to link to corresponding issue.Because when everyone completes this issue, it will be closed manually.

**Comment by zhicheng-ning** [comment]
code has been merged in #12

**Pull request closed without merging**
